export const urls = {
  homeUrl: '/',
  jsWebUrl: '/js-web',
  urlAll: '/*',
  historyUrl: '/history',
  ecmaUrl: '/ecma',
  jsxjUrl: '/js-java',
  jstUrl: '/js-today',
  counterAppUrl: '/counter-app',
  todoListUrl: '/todo-list',
  hackerTyperUrl: '/hackertyper',
  memoryGameUrl: '/memory-game',
  mortgageCalculatorUrl: '/mortgage-calculator',
  blogUrl: '/blog',
  blogArticlesUrl: '/articles',
  blogCreateUrl: '/create-new-article',
  blogArticleDetailUrl: '/article-detail/',
} as const
