export const urls = {
  homeUrl: '/',
  jsWebUrl: '/js-web',
  urlAll: '/*',
  historyUrl: '/history',
  ecmaUrl: '/ecma',
  jsxjUrl: '/js-java',
  jstUrl: '/js-today',
  counterAppUrl: '/counter-app',
  todoListUrl: '/todo-list',
  hackerTyperUrl: '/hackertyper',
  memoryGameUrl: '/memory-game',
  mortgageCalculatorUrl: '/mortgage-calculator',
  backendUrl: '/http-filter',
  apiUrl: process.env.REACT_APP_USERS_API_URL,
}
